// Shared portfolio data — used across all 3 variations
window.PORTFOLIO_DATA = {
  name: "Cao Thanh Huy",
  role: "Software Engineer",
  tagline: "Backend engineer building real-time systems, REST APIs, and distributed architectures.",
  location: "Vietnam",
  email: "thanhhuyna1410@gmail.com",
  github: "github.com/huypro2005",
  githubUrl: "https://github.com/huypro2005",

  about: {
    short: "I'm a software engineer focused on backend systems — designing APIs, modeling data, and shipping services that scale.",
    long: "I build the unglamorous half of the stack. Most of my work lives on the server: designing REST APIs, modeling relational schemas, wiring up real-time websockets, and containerizing services so they run identically on my laptop and in production. I gravitate toward problems that involve concurrency, state synchronization, and clean system boundaries. Currently looking for a backend internship where I can learn from senior engineers and contribute to a real production codebase.",
  },

  stack: {
    languages: [
      { name: "Python", level: 90 },
      { name: "Java", level: 80 },
      { name: "SQL", level: 85 },
      { name: "TypeScript", level: 60 },
    ],
    frameworks: [
      { name: "FastAPI", note: "REST APIs, async" },
      { name: "Django + DRF", note: "Full-stack web apps" },
      { name: "Django Channels", note: "WebSocket, ASGI" },
      { name: "Spring Boot", note: "Java enterprise" },
      { name: "STOMP / SockJS", note: "Real-time messaging" },
    ],
    data: [
      { name: "PostgreSQL", note: "Primary OLTP" },
      { name: "MySQL", note: "Schema design, Flyway" },
      { name: "Redis", note: "Cache, pub/sub, broker" },
      { name: "SQLAlchemy", note: "ORM, migrations" },
    ],
    infra: [
      { name: "Docker", note: "Compose, multi-service" },
      { name: "AWS / GCP", note: "Deployment basics" },
      { name: "Celery", note: "Task queues" },
      { name: "Gunicorn / Daphne", note: "WSGI / ASGI" },
      { name: "JWT / OAuth2", note: "Auth flows" },
    ],
  },

  specialties: [
    { title: "REST & GraphQL API Design", desc: "Versioned endpoints, OpenAPI specs, JWT auth, rate limiting." },
    { title: "System Design", desc: "Service boundaries, data modeling, caching strategies, async pipelines." },
    { title: "Real-time Systems", desc: "WebSocket protocols (STOMP, Channels), pub/sub via Redis, reconnect logic." },
  ],

  projects: [
    {
      id: "chat",
      name: "Multi-Chat",
      subtitle: "Real-time chat platform",
      year: "2026",
      period: "Apr — May 2026",
      role: "Backend Engineer",
      stack: ["Java 21", "Spring Boot 3.4", "PostgreSQL 18", "Redis 7", "STOMP", "Flyway"],
      problem: "Build a Slack-like chat app supporting 1-1 and group conversations with reactions, read receipts, file sharing, and reliable reconnect.",
      contribution: [
        "Designed PostgreSQL schema with Flyway migrations for users, conversations, messages, reactions, attachments.",
        "Implemented STOMP/SockJS WebSocket layer for typing indicators, message delivery, and reconnect catch-up.",
        "Built file upload service supporting 14 MIME types with Apache Tika validation and Thumbnailator for image previews.",
        "Wired Google OAuth + JWT auth and bilateral block/unblock semantics across REST + WS layers.",
      ],
      metrics: [
        { label: "MIME types", value: "14" },
        { label: "Pinned/conv", value: "3 max" },
        { label: "Services", value: "4" },
      ],
      url: "https://github.com/huypro2005/Multi-Chat-Using-Java",
      demoUrl: null,
      videoUrl: null,
      screenshotUrl: null,
      mediaType: "diagram",
      tags: ["real-time", "auth", "websockets"],
    },
    {
      id: "realestate",
      name: "RealEstate Platform",
      subtitle: "Property management + ML price prediction",
      year: "2025",
      period: "Aug — Dec 2025",
      role: "Full-stack — owned backend",
      stack: ["Django 5.2", "DRF", "Channels", "MySQL", "Redis", "Celery", "Scikit-learn"],
      problem: "Real estate marketplace with listings, real-time chat between buyers/sellers, news system, and ML-powered price prediction.",
      contribution: [
        "Built Django REST API with Swagger docs covering Properties, Auth, Comments, Notifications, and Favorites.",
        "Integrated Django Channels (ASGI via Daphne) + Redis backplane for real-time buyer-seller chat.",
        "Trained scikit-learn regression model for housing price prediction; served via Celery worker for async inference.",
        "Configured Celery + Redis broker for background jobs (notification fanout, image processing, model inference).",
      ],
      metrics: [
        { label: "Modules", value: "11" },
        { label: "Commits", value: "95" },
        { label: "ML Model", value: "Regression" },
      ],
      url: "https://github.com/huypro2005/Manage_and_Predict_House_Price",
      demoUrl: null,
      videoUrl: null,
      screenshotUrl: null,
      mediaType: "schema",
      tags: ["django", "ml", "websockets"],
    },
    {
      id: "bot",
      name: "Bot-Education-Auth",
      subtitle: "School management — FastAPI + Telegram bot",
      year: "2025",
      period: "2025",
      role: "Backend Engineer",
      stack: ["FastAPI", "SQLAlchemy", "MySQL 8", "Telegram Bot API", "OpenAI", "Docker"],
      problem: "School management system with two interaction channels: Admin Web (REST) for staff and a Telegram bot for teachers/students, including AI-powered assignment grading.",
      contribution: [
        "Architected FastAPI backend with separate routers for /admin/* and bot handlers, sharing SQLAlchemy ORM models as single source of truth.",
        "Implemented JWT auth with refresh tokens for the admin web and Telegram chat-id binding for bot users.",
        "Integrated GPT-4.1-mini for auto-grading PDF submissions and evaluating student conduct/learning.",
        "Set up production Docker Compose with daily MySQL backup cron container and documented every deploy issue I hit (umask, UID mismatch, init scripts).",
      ],
      metrics: [
        { label: "Services", value: "3" },
        { label: "Channels", value: "Web + TG" },
        { label: "AI", value: "GPT-4" },
      ],
      url: "https://github.com/huypro2005/Bot-Education-Auth",
      demoUrl: null,
      videoUrl: null,
      screenshotUrl: null,
      mediaType: "flow",
      tags: ["fastapi", "bot", "ai"],
    },
    {
      id: "data",
      name: "Housing Price Analysis",
      subtitle: "Data analysis + ML prototype",
      year: "2026",
      period: "Jan — May 2026",
      role: "Solo",
      stack: ["Python", "Pandas", "NumPy", "Scikit-learn", "Jupyter"],
      problem: "Exploratory data analysis on housing market data — feature engineering and baseline regression model that later powered the RealEstate platform.",
      contribution: [
        "Cleaned and imputed raw housing dataset; encoded categorical features and engineered location-based predictors.",
        "Compared Linear Regression, Random Forest, and Gradient Boosting baselines on RMSE.",
        "Exported best model with joblib for downstream serving.",
      ],
      metrics: [
        { label: "Models", value: "3" },
        { label: "Notebooks", value: "EDA" },
      ],
      url: "https://github.com/huypro2005/Data-Analysis-And-Predict-Housing-Price",
      demoUrl: null,
      videoUrl: null,
      screenshotUrl: null,
      mediaType: "chart",
      tags: ["data", "ml"],
    },
    {
      id: "xiangqi",
      name: "Xiangqi (Chinese Chess)",
      subtitle: "Desktop game with AI opponent — C# WinForms",
      year: "2025",
      period: "Oct — Dec 2025",
      role: "Solo — IT008 course project",
      stack: ["C#", "WinForms", ".NET 9", "OOP"],
      problem: "Build a full Chinese Chess (Cờ tướng) desktop game supporting both PvP (2-player local) and PvE (vs AI) modes, with custom-rendered board, piece movement rules, and audio.",
      contribution: [
        "Designed OOP class hierarchy: BasePiece abstract class with subclasses for each piece type (Tướng, Sĩ, Tượng, Xe, Pháo, Mã, Tốt) encapsulating per-piece movement rules.",
        "Implemented core game logic in logic.cs — turn management, legal-move validation, check/checkmate detection on the 9×10 board.",
        "Built AI opponent (AI_Run.cs) for PvE mode using move evaluation; custom BoardRenderer for drawing pieces and highlighting valid moves.",
        "Added multi-screen WinForms UI (Home / Setting / About) with audio manager for background music and move sound effects.",
      ],
      metrics: [
        { label: "Modes", value: "PvP + PvE" },
        { label: "Piece types", value: "7" },
        { label: "Language", value: "C# 100%" },
      ],
      url: "https://github.com/huypro2005/Xiangqi_IT008",
      demoUrl: null,
      videoUrl: null,
      screenshotUrl: null,
      mediaType: "flow",
      tags: ["desktop", "game", "ai"],
    },
    {
      id: "airport",
      name: "Airport Management System",
      subtitle: "Flight ops + ticketing — Flask REST API",
      year: "2024",
      period: "Feb — May 2024",
      role: "Backend — SE104 course project",
      stack: ["Flask 3.1", "SQLAlchemy 2.0", "MySQL 8", "JWT", "Gunicorn", "Docker", "VNPay"],
      problem: "Build an end-to-end airport management system: flight scheduling with intermediate airports, ticket booking with online payment, passenger/staff management, and revenue reporting — all behind a documented REST API.",
      contribution: [
        "Designed MySQL schema (13 tables) covering flights, airports, tickets, passengers, staff, ticket classes, intermediate stops, and monthly/yearly revenue aggregates with SQLAlchemy ORM models.",
        "Built REST API with 30+ endpoints across 11 route modules; documented every module via Swagger UI and per-module README files.",
        "Implemented JWT auth with role-based access (Admin/User) and integrated VNPay payment gateway for ticket purchases with return-URL verification.",
        "Set up APScheduler for daily revenue rollups, Flask-Migrate for schema changes, and dockerized the stack with Gunicorn + Compose for production deploy.",
      ],
      metrics: [
        { label: "Endpoints", value: "30+" },
        { label: "Tables", value: "13" },
        { label: "Commits", value: "43" },
      ],
      url: "https://github.com/huypro2005/airport",
      demoUrl: null,
      videoUrl: null,
      screenshotUrl: null,
      mediaType: "schema",
      tags: ["flask", "rest", "payments"],
    },
  ],

  timeline: [
    {
      year: "2026",
      period: "May 2026 — Present",
      title: "Backend Engineer Intern (Seeking)",
      org: "Open to opportunities",
      desc: "Looking for an internship where I can contribute to a real production codebase and learn from senior engineers.",
      tag: "current",
    },
    {
      year: "2026",
      period: "Apr — May 2026",
      title: "Multi-Chat — Real-time chat platform",
      org: "Personal",
      desc: "Built a Slack-like chat app with Spring Boot 3.4 + STOMP/SockJS WebSockets, PostgreSQL with Flyway migrations, Google OAuth + JWT, and file uploads with Apache Tika validation.",
      tag: "build",
    },
    {
      year: "2026",
      period: "Jan — May 2026",
      title: "Data Analysis & ML Foundations",
      org: "Self-study",
      desc: "EDA on housing market data; compared Linear Regression, Random Forest, Gradient Boosting on RMSE. Output later powered the RealEstate platform's price predictor.",
      tag: "learn",
    },
    {
      year: "2025",
      period: "Oct — Dec 2025",
      title: "Xiangqi (Chinese Chess) — IT008",
      org: "Course project",
      desc: "C# WinForms desktop game supporting PvP and PvE modes. Designed OOP piece hierarchy, custom board renderer, and AI move evaluation.",
      tag: "build",
    },
    {
      year: "2025",
      period: "Aug — Dec 2025",
      title: "Full-stack Real Estate Platform",
      org: "Course / Personal",
      desc: "Owned the backend for a property marketplace with real-time chat (Django Channels + Redis), ML price prediction (scikit-learn), and Celery task queues.",
      tag: "build",
    },
    {
      year: "2025",
      period: "2025",
      title: "Bot-Education-Auth",
      org: "Personal",
      desc: "School management system with FastAPI admin web + Telegram bot, sharing SQLAlchemy models. Integrated GPT-4.1-mini for auto-grading PDF submissions.",
      tag: "build",
    },
    {
      year: "2024",
      period: "Feb — May 2024",
      title: "Airport Management System — SE104",
      org: "Course project",
      desc: "Flask REST API with 30+ endpoints, 13 MySQL tables, JWT auth with role-based access, VNPay payment integration, and dockerized deployment with Gunicorn.",
      tag: "build",
    },
    {
      year: "2023",
      period: "Sep 2023",
      title: "Started university",
      org: "Computer Science",
      desc: "Began coursework focused on systems, databases, and distributed computing.",
      tag: "milestone",
    },
  ],

  blog: [
    {
      title: "Why I document every Docker deploy bug I hit",
      excerpt: "umask 077, UID mismatches, crontab EOFs — the small stuff costs hours when you're alone. Here's my errors_fix.md template.",
      date: "Oct 2025",
      readTime: "4 min",
      tag: "DevOps",
    },
    {
      title: "STOMP vs raw WebSockets: what I learned building a chat app",
      excerpt: "STOMP gave me message routing for free, but the framing overhead matters at scale. A breakdown from my Multi-Chat project.",
      date: "Sep 2025",
      readTime: "6 min",
      tag: "Real-time",
    },
    {
      title: "Sharing SQLAlchemy models between a FastAPI app and a Telegram bot",
      excerpt: "How I avoided drift between two interfaces by treating models.py as the single source of truth.",
      date: "Aug 2025",
      readTime: "5 min",
      tag: "Architecture",
    },
  ],

  github_stats: {
    repos: 12,
    contributions: 480,
    streak: 47,
    languages: [
      { name: "Python", pct: 42, color: "#3776ab" },
      { name: "Java", pct: 28, color: "#f89820" },
      { name: "TypeScript", pct: 18, color: "#3178c6" },
      { name: "Other", pct: 12, color: "#94a3b8" },
    ],
  },
};
